whitelist-worlds:
  - world_ignored
# Reset Time: TimeUnit: minute
reset-time: 60
limit: 1000
whitelist-spawnreason:
  - BEEHIVE
  - BREEDING
  - BUILD_IRONGOLEM
  - BUILD_SNOWMAN
  - BUILD_WITHER
  - COMMAND
  - SPAWNER
  - SPAWNER_EGG
  - EXPLOSION