whitelist-worlds:
  - world_ignored
limit: 300
whitelist-spawnreason:
  - BEEHIVE
  - BREEDING
  - BUILD_IRONGOLEM
  - BUILD_SNOWMAN
  - BUILD_WITHER
  - COMMAND
  - SPAWNER
  - SPAWNER_EGG
  - EXPLOSION