name: ChunkHeat
version: ${project.version}
main: com.ghostchu.chunkheat.ChunkHeat
api-version: 1.13
authors: [ Ghost_chu ]
description: The mob farme breaker
commands:
  chunkheat:
    description: chunk heat
    usage: /chunkheat
